name: 'Convert AsciiDoc to PDF'
description: 'Greet someone'
inputs:
  input_dir:
    # description: 'hogehoge'
    required: true
  output_dir:
    # description: 'hogehoge'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: Write-Output "Hello World."
      shell: pwsh

    - name: Set GitHub Path
      run: (Resolve-Path ${{ github.action_path }}).Path >> $Env:GITHUB_PATH
      shell: pwsh

    # - name: Run goodbye.sh
    #   run: goodbye.sh
    #   shell: bash
