name: 'Convert AsciiDoc to PDF'
description: 'Greet someone'
inputs:
  input_dir:
    # description: 'hogehoge'
    required: true
  output_dir:
    # description: 'hogehoge'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello World"
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Run goodbye.sh
    #   run: goodbye.sh
    #   shell: bash
